Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drvers.
src = Split("""
board.c
drv_led.c
drv_usart.c
drv_uart.c
""")

# add SPI drvers.
if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']
# add Ethernet drvers.
if GetDepend('RT_USING_DFS'):
    src += ['msd.c']

# add Ethernet drvers.
if GetDepend('RT_USING_RTC'):
    src += ['rtc.c']

# add Ethernet drvers.
if GetDepend('RT_USING_RTGUI'):
    src += ['touch.c']
    if rtconfig.RT_USING_LCD_TYPE == 'ILI932X':
        src += ['ili_lcd_general.c']
    elif rtconfig.RT_USING_LCD_TYPE == 'SSD1289':
        src += ['ssd1289.c']

    
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
